### ISSUE TITLE
Array's enum's empty default breaks if deleting an array element

### ISSUE THREAD

**Issue by gradinkov** [json-editor/json-editor#41] opened 2018-04-05 22:23 UTC
If an array's enum's default is { }, and you delete any array element, you're unable to select the enum anymore.

Related: https://github.com/jdorn/json-editor/issues/813

**Comment by germanbisurgi** [comment] 2018-05-30 12:27
Hi Gradinkov. I need your schema to understand, reproduce and maybe find a solution to your problem :)

**Comment by pmk65** [comment] 2019-01-15 11:10
@gradinkov Please provide a sample schema or this issue will be closed.

**Comment by pmk65** [comment] 2019-01-29 12:09
Closing issue due to lack of schema/feedback.

**Closed by pmk65** 2019-01-29 12:09 UTC
Labels: needs feedback
