### ISSUE TITLE
Base64 (Multiple Upload) - Deleting file always deletes the last file instead of the one clicked

### ISSUE THREAD

**Issue by TheJesper** [json-editor/json-editor#1237] opened 2022-12-05 10:49 UTC
### General information
- json-editor version: 2.8.0

### Expected behavior
Selected file to be removed

### Actual behavior
The last file is always removed

### Steps to reproduce the behavior
1. Click Load examples 
2. Click Base64 (MultipleUpload)
3. Upload 3 files
4. Click bin to remove the first file

Direct link to example: https://pmk65.github.io/jedemov2/dist/demo.html

```

**Comment by schmunk42** [comment] 2022-12-16 15:11
I can't reproduce.

Could you provide a screencast?

**Comment by TheJesper** [comment] 2022-12-17 19:16
Hi, looking in to this further have given some more clarity. The files are renamed on delete so the title will still be **Image 1** which might be a little bit confusing, however that is "by design" i guess. 

A real gui-issue though is that the "Choose file" still holds the same file-name after it has been removed. 

Also after removing all files - and adding a new one... The file name is cached:

![image](https://user-images.githubusercontent.com/7533879/208261142-fb14ae75-57b1-43bf-97ab-a2f9c04990a2.png)

https://user-images.githubusercontent.com/7533879/208260972-c77e7825-4489-48b3-9102-cc24e5eb3728.mp4

Thanks in advance for looking in to this...

**Comment by germanbisurgi** [comment] 2023-05-11 13:15
Thank you for reporting this. I was testing this issue and came to the conclusion that when an item is deleted, the editor file input displays the incorrect filenames because the array editors do a "soft" delete and reuse already created elements seting their values again. This works for almost all inputs except the type file ones because of security reasons.

Nonetheless the editor values are still set correctly (base64 data) and the preview data is also set correctly (type, size and image).

To address this issue, one potential solution could be to hide the real input file (and the filenames with it), and instead, add a UI upload button that triggers the original button on click. I made a video to demo this solution using a local copy.


https://github.com/json-editor/json-editor/assets/13135260/d7e2e50d-46e4-4939-a5bb-eaef099fc4b2

**Comment by germanbisurgi** [comment] 2023-05-15 10:25
@marc7000 @schmunk42 what do you think?

**Comment by schmunk42** [comment] 2023-05-15 11:18
Does this also work on Mobile Devices?

**Comment by schmunk42** [comment] 2023-05-15 15:52
@handcode @eluhr Your opinions?

I think it's the most consistent way...

**Comment by germanbisurgi** [comment] 2023-07-03 13:19
Fixed in 1366

**Closed by germanbisurgi** 2023-07-03 13:19 UTC
