### ISSUE TITLE
object.js renders invalid HTML code

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#214] opened 2018-11-12 10:50 UTC
All themes render invalid HTML due to repeatedly using the same Id for different elements. This is repeated through all themes.

### Code from src/themes.js
Note the dual use of "id=pName" in both functions.

```javascript
  getTabHolder: function(propertyName) {
    var pName = (typeof propertyName === 'undefined')? "" : propertyName;
    var el = document.createElement('div');
    el.innerHTML = "<div style='float: left; width: 130px;' class='tabs' id='" + pName + "'></div><div class='content' style='margin-left: 120px;' id='" + pName + "'></div><div style='clear:both;'></div>";
    return el;
  },
  getTopTabHolder: function(propertyName) {
    var pName = (typeof propertyName === 'undefined')? "" : propertyName;
    var el = document.createElement('div');
    el.innerHTML = "<div class='tabs' style='margin-left: 10px;' id='" + pName + "'></div><div style='clear:both;'></div><div class='content' id='" + pName + "'></div>";
    return el;
  },
```

**Comment by pmk65** [comment] 2018-11-12 14:17
The id value is potential invalid too, as it's based on the editor title.

Example "src/editors/array.js" generates the id like this (line 117):
````javascript
this.theme.getTabHolder(this.getItemTitle());   
````
So the "pName" var needs to be sanitized before being used as id.

**Comment by pmk65** [comment] 2018-11-14 20:11
I have been looking at the problem with categories not working in most themes and fixed one of the problems with invalid IDs. But there's another related problem that might be the cause of the themes problems.

If you look at this [example](https://json-editor.github.io/json-editor/?schema=N4IgLglmA2CmIC4QAUBOB7AVrAxmAziADTgCeADvEugEbZ7EgBm6qAtgIZiIg5ewBzVhFiES5DJVSRRiUEwip83BKEgwqIAGKLlAAgAqHGozAVNtet3GTY0kYVUgAdhzZU15nstQRnA0yg4HgA5N3gSNj8AGVh/MAALRABGEgATWCYOAFdoFRAAQWgaO24AXxIOAQ8ySm8wX39AjR4C6sYMrNz85OSQMoGSfFx0ZzS5cCDNAGURscNjUy9qOlxrEAl0KRlHUFd3CbM6pB8/AJJ1YKQwg8iYuIFElPTMnLyeACFafsr2pyPNKcmhcpq12i8uu8kAAmaH9AYDIAAA=&value=N4IgZglgTgzgLiAXKAdgQwLYFMkgIIA2ARllAgDQhoDmOiIAjAyAL6UxYDGA9igCZJUmOiABC3IiEo0RAJlmsWQA&prompt_before_delete&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&show_errors=interaction): (Doesn't matter which theme you use),
Then try to inspect the content of the first tab (category) and you'll notice that the content is wrapped in 4 identical blocks.

````html
<div class="col-md-12" role="tabpanel" id="First Tab">
  <div class="row">
    <div class="col-md-12" role="tabpanel" id="First Tab">
      <div class="row">
        <div class="col-md-12" role="tabpanel" id="First Tab">
          <div class="row">
            <div class="col-md-12" role="tabpanel" id="First Tab">
              <div class="row">
                <div data-schematype="object" data-schemapath="root.first" style="position: relative;" class="col-md-12">
````
I can't see any reason why it has to be wrapped 4 times, and it clearly poses a problem with 4 identical IDs.

**Comment by pmk65** [comment] 2018-11-29 12:21
The categories/tabs (and the bug) was introduced in #85, which looks like a huge merger so I can't see who is the original author.

**Comment by schmunk42** [comment] 2018-11-29 12:56
I can't really remember the discussion, only that it was rather complicated and that there were several PRs.
Could we catch something like this in tests?

**Comment by pmk65** [comment] 2018-11-29 19:05
> 
> 
> Could we catch something like this in tests?

We could probably test if the output produced is valid HTML, but I don't think we can catch errors like the multiple wrappings.

**Comment by pmk65** [comment] 2018-12-05 13:57
> 
> 
> I can't really remember the discussion, only that it was rather complicated and that there were several PRs.

I located it to this [PR](https://github.com/json-editor/json-editor/pull/85/commits/dc6a71436688aaaf18fdcb8af9891fbafcbc080a). Seems to originate from this [fork](https://github.com/heathdutton/json-editor). But the issue tracker there is disabled so I can't see any conversations, only that it looks like the original author is @pmadril

**Comment by pmadril** [comment] 2018-12-05 14:44
Hi, I'm author of categories. As soon as possible I will take a look at the problem (just few hours, I'm in a rush rigth now).

**Comment by pmk65** [comment] 2018-12-05 22:09
> 
> 
> Hi, I'm author of categories. As soon as possible I will take a look at the problem (just few hours, I'm in a rush rigth now).

Great. I hate to admit it, but I just can't pinpoint the exact place where it happens. So I really hope you can help fix this.

**Comment by pmadril** [comment] 2018-12-11 15:07
Hi, news from the front: Sorry by the delay. I submitted a https://github.com/json-editor/json-editor/pull/243 that solves this issue. Materialize still doesn't support tabs-top or categories because the code to do that isn't there. I will still work on it and submit another PR.

**Comment by pmadril** [comment] 2018-12-11 16:34
Sorry, please do not merge. Is not working after merging with master last commits.

**Comment by pmadril** [comment] 2018-12-11 16:48
Sorry again, I really need somebody else than not me testing this. It seems that everything is ok and my test environment had problems.

**Comment by pmadril** [comment] 2018-12-11 19:03
I'm out of home now, I will check asap. Seems not a big deal.

**Comment by pmadril** [comment] 2018-12-13 02:11
@pmk65 I'm trying to analyze the initial Tab not active problem without success. 
How can I do to reproduce it?
Thanks a lot.

**Comment by schmunk42** [comment] 2018-12-13 07:37
Would be great to have a test for this.

**Comment by pmk65** [comment] 2018-12-17 23:18
@pmadril Sorry for the late reply, but I have been down with the flu the last couple days.
It was just a quick test, but I will make a more thorough test and post my results here.

**Comment by pmk65** [comment] 2018-12-27 15:52
@pmadril I tested it more intensively, and couldn't reproduce the error. So most likely I forgot to rebuild the dist files before testing. 😄 
Every theme works perfectly as far as I can see, except for the Materialize theme. But you also mentioned that on the PR. 
So I think it's ok to merge this.

**Comment by schmunk42** [comment] 2018-12-31 12:47
@pmk65 Can we close this, since #243 is merged?

**Closed** 2018-12-31 12:55 UTC
Labels: bug, help wanted
