### ISSUE TITLE
JSONEditor as react component

### ISSUE THREAD

**Issue by VadimTikhonyuk** [json-editor/json-editor#684] opened 2020-03-10 10:53 UTC
### General information
I want to use JSON editor in Create React App,
handling data file with  more than 50kb size takes infinity to parse and display form

this editor https://react-jsonschema-form.readthedocs.io/en/latest/ can handle large data  files in seconds, and I believe that because it using react.

- json-editor version: 2.1

### Expected behavior
nice and tidy article in wiki about how to make it work with react
or at least how to handle large arrays (current article didn't provide enough info)

### Actual behavior
4 issues, where only one gives some potential useful info, but it was in 2018 and doesn't work for me
`import JSONEditor from '@json-editor/json-editor'` return undefined

**Comment by schmunk42** [comment] 2020-03-10 12:46
Duplicate of https://github.com/json-editor/json-editor/issues/628

Related: https://github.com/json-editor/json-editor/issues/40

**Comment by VadimTikhonyuk** [comment] 2020-03-10 13:41
links that you provide didn't contain solution

**Comment by schmunk42** [comment] 2020-03-10 15:37
No, it's still an open issue, but it's the same, isn't it?

**Closed by schmunk42** 2020-03-10 15:37 UTC
