### ISSUE TITLE
Choose which oneOf is used with startval

### ISSUE THREAD

**Issue by sluc23** [json-editor/json-editor#166] opened 2018-09-03 11:57 UTC
This is following-up ticket, from old repo one: https://github.com/jdorn/json-editor/issues/795

Is there a way to choose which of a "oneOf" is used when using startval?

**Comment by wclssdn** [comment] 2018-09-06 03:06
Duplicate of #128 
Some way to resolve simple forms

**Comment by sluc23** [comment] 2018-09-13 11:05
ok @wclssdn , but doesn't work for complex objects..
maybe instead os using `startval` I will try with loading a json with `editor.setValue()`

**Comment by wclssdn** [comment] 2018-09-27 10:20
> ok @wclssdn , but doesn't work for complex objects..
> maybe instead os using `startval` I will try with loading a default json with `editor.setValue()` on ready event

if you reslove this, please tell me~ thanks~

**Comment by pmk65** [comment] 2019-01-11 15:37
Seems like this is no longer an issue as there's no feedback from the poster.
So I guess this one can be closed.

**Closed** 2019-01-11 15:38 UTC
Labels: needs feedback

**Comment by Vafa-Andalibi** [comment] 2019-09-01 23:50
Any sample on this? I can't find any. No answer in [#795](https://github.com/jdorn/json-editor/issues/795) either
