### ISSUE TITLE
Adding object to an array-of-objects includes unwanted object

### ISSUE THREAD

**Issue by fangq** [json-editor/json-editor#246] opened 2018-12-15 00:10 UTC
sorry, I am new to JSON schema and json-editor. I have a JSON structure made of an array of objects, see example here

https://github.com/fangq/mcx/blob/72afd6a0bebcca6a83735aa215d07125f1c5bee1/README.txt#L549-L582

the number of objects in the "Shapes" array may vary. I adapted the example from json-editor and try to make an editor for this JSON input, but somehow, creating the Shapes object is not working with json-editor. I suspect that I wrote incorrect schema, but could not find examples how to do this properly.

here is my html editor based on json-editor:

https://github.com/fangq/mcx/blob/etherdome/mcxone/index.html

this schema is what I used for this object is

https://github.com/fangq/mcx/blob/etherdome/mcxone/index.html#L359-L582

I changed oneOf to anyOf, but still have the same issue. Can someone tell me what I did wrong?

thanks

**Update Mar 3, 2021**
================================

The updated json editor for my schema can be found at 

http://tinyurl.com/y9vynjxy

or using the json editor playground link

http://tinyurl.com/ymr9bzhn

the issue is now related to the extra object when adding constructs to the Shapes tab. see updated comments at https://github.com/json-editor/json-editor/issues/246#issuecomment-790189281

**Comment by schmunk42** [comment] 2018-12-17 14:04
Did you take a look at the validation errors, i.e. [here](https://json-editor.github.io/json-editor/?schema=N4IgLglmA2CmIC4QGVZkgOwOYGcQBpwBPAB3iQHsAjAK1gGMwCQAnWARwFcI2ATRANopYOHBAoZmAMQosA7gEMW/QgHkSYCr3iFkACwVk8hACIUAtgoiSAuoQBmsy0yT0FYWFlkQRzEiwoyFkhfBFBUUXFJMOIyRBBqOkZmSBhyYUiJZkcWZ3isFggVVg5uPkEQAEkTZgAFPQpNDGMQMwBZCBxnej1mMwBBTk0AFT02BX47EH9A2GCfPBjqxFBUuHiIsQkAAgA5BXMdWPScMELsZm17BU5oFxBzegAPEABfQnrGiUXVqHWkT5NbYYTjmKhzFKkdLWDxYCGEK43O6IACMAAYMRjCJYnhBzKDUZiie9WhQOl13D0VuA/ukzNsAEqwexwRhRSFxJBUCgUOAKSQI5lIlxnTiwEkDIYUUbjfgxNbpAAyaG2bQAwgANbbaehFWDbMBjWATAD0VGgFHoAGttmIAF5HMBQ+Lc3nGgUgRG3EUsMUkhm7ADiqFgct+aXiDP5vAsttgoY56RBYPhnqF3sQACYAJxolGZgDM2czr1LhBk8iUYeO8USDCYhAV8QrimU2Sc7nyhWKbC4PATCCEwzRzGGKL6TCmMyCIR+IGH1KbSGQYCUmCwBrxjudSGT4JYl3TyIQaOx1jxBJP2IUuPx5lRsAAtAB2Eljxe0+IAUQwvGsG8gQ5E3iPdUy9Y8AFYn2zM8MAve8rweG94IfF8JRccN/nnLdtiwdx9TkIpDWA3dQX3Q9rgzBAoMfGCHnPO9EFPJDb0vFEn1fMsQHUTRtEXHcEloesUk/JAeK0I5ezKAchGQChOBYeh4CnAIZwWak5IUpSPwjZd5MU7dOUEpIGxKPtykHednQ+CgWhMHgQBU2Z5lCUBhh3TD0ncuJGwE05ziwCjhXiMgMF1aBmFgZMKlC8LmE6RpVIgehmHoCQjjwzhIn5PxoH5JQ/HcDwWA9EgirmDAC2KRwFJ8A9CCUegxAwI4/xwK121quYXgcfS6qeTNijtTLso9aBrCOHBxtM2KIDylgWAUIhHJJWpbJ0rC1rESAsl8oylEW5betyTskFXKgWigWBzDnJ0jNAg8SXAlwBALU83vwNEpnMaxKg8G7EALa8nj+67FgLCUHPlUSQEVG4wr0bZ7LYNldprJADqW9sTvuc6WmewRT1PFEpiugH5QEh63lg0HyaBljacWAAWValAOcdod0lB9KU7ZajZw5iu2cc9vSTGjpAHI8jOhQLvi/7bspsiIRJH6MEZxAmeBjWEBZj4BczDb0k0gy+YFtA5mFkiQHF7HpfAWXLoV/j7uVx6aed3Xtc9lmuJMC3GFkI34n9jxA/q9GbYWrHjvt871kIMnFaMutkkIKT+zlIQtuYBlHMIac5lnakc85zbbKgdlRfiW3E891YlZTd36PVz36ZxHWIcIPOy/SKM/yy62qcFSjj0zWCUJPUtp5JfRDFcmkubnoxrdryWO1x2WE5AJPqXS1R7EETz4kDbtrdT0zd5iQuXLnYYFEC3v4nvwLq6QGFPFTNXJ7RWeIAdYOy5/6GTFtHCWUtToOzlnXMGLskxu2pi3Tu3tYEIAhtPfAx9lwkD0HMEBtYhJp2mKpIu6kYgv0AfOB+1sP5wgjt/RiU81CULVFFYqq8wF20gXjeWqCG6uybogtWyCGZt39JQ/uEBB5vxAMPFuP8MFYJAAAIQoD1SOF8/AkNvtSChT8kAUJkbQr+DFLy/10MAyhyBLEyLXhAze0Cd710jlTVWv024oLpiSVQLC2GpjuqAw6XCHFOz4S4hBbjW6oPbjeTuijF5YWQJwKgBQijn0ITNbRxdyHUP0VQ1+kdjH0NMQhcxKBLF5OsQA2xnDY7cMdrw8m/D4GCMiSIjuYjmF5NYRgdhNSgl1JCY05OLTyJtI8aI6J8SlwgDVEQcav5/ECU0QXLJZC3K5KUYYwpvTP7FLgowspaoRyVJsZHOxG94g8JgU08JrSPbRM8eDEkaoOZKJ6X085tT144yuQ0m5IyQIRIeXTJ5gNxF5MkdIu55EJ6HOmTDfYQEZH+X/G8GwfsLBWGiM0ghJkRJczMJYawzAM4WSEG0UMEAFB9DxMwVQhQsDWG8spVZzlsmgAZRAJlGAWWUK5Ty7Y7htgCCJp9Gw1tXR8g9ATBAopxSmDpXk+yhxmhRBaAEmu3z7F/McVfXF79dl0KEe4x5kyvGEAAGq8lBLAKQc1yBKOtdAW12x7Xb01UgVFFwR7BSQIgylf4aV5MDdSjhAyflxy3kcYRntx5OLCZ64ywl06lEzhUfENLsTQoKbYNlakF6Zsof0C6sgNBRG2AACkAD3AChhYmnMOYAAlEPBBvqqLMQYWY1Wg9KluHQHMf8Vbq04HrY2ltMi5Gys7SUpiJJH5KP6HBHAiVAhECrVgCdMKwJHhcCiOFl5Hz7pYpPFEJIcUJL7syVkkAABu+pKiLKeFWjAW6k1Tt3aiA9pSZ4zyAAAA=&value=N4IgygpgzlCWD2A7EAuUBJAIqkBbAxgB4gA0IACgBbwAuSUqAjAAyutmbwCysUuAhjXyVUNAE4BXCB3gBBCXQAqlMRH4ATUZIgBfMgDF4YgO78xmtCEXNUzMosaoArBAC0ATg41nb93pAA8gAOdOoQqKBg8BJi+OGWigCeQfEgKYj4sAA2pBTwDCgA2gDMdqUkzAC6HLBiqIV2doyVOv5glPwpBYWgivwA5rZkAfWIEllZJGMTU+NZ1SAASrY6C5wCsMiWAWKw/ZtJKVpSNbijc7Mz0/NkXBDqsPz1oLgSTyh2eBIFn4MojGQtow9C83kMvj8yH8ASAgatWkAAA=&prompt_before_delete&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction)

```
[
  {
    "path": "root.Shapes.0",
    "property": "oneOf",
    "message": "Value must validate against exactly one of the provided schemas. It currently validates against 4 of the schemas."
  },
  {
    "path": "root.Shapes.0.oneOf[4].C0.0",
    "property": "type",
    "message": "Value must be of type number"
  },
  {
    "path": "root.Shapes.0.oneOf[4].C0.1",
    "property": "type",
    "message": "Value must be of type number"
  },
  {
    "path": "root.Shapes.0.oneOf[4].C0.2",
    "property": "type",
    "message": "Value must be of type number"
  },
  {
    "path": "root.Shapes.0.oneOf[4].C1.0",
    "property": "type",
    "message": "Value must be of type number"
  },
  {
    "path": "root.Shapes.0.oneOf[4].C1.1",
    "property": "type",
    "message": "Value must be of type number"
  },
  {
    "path": "root.Shapes.0.oneOf[4].C1.2",
    "property": "type",
    "message": "Value must be of type number"
  },
  {
    "path": "root.Shapes.0.oneOf[5]",
    "property": "type",
    "message": "Value must be of type string"
  }
]
```

Looks like the oneOf/anyOf selections must be more unique.

**Comment by fangq** [comment] 2019-05-19 20:28
@schmunk42, sorry for the long delay. finally have time to look at this again. 

I managed to fix the validation errors (by replacing oneOf to anyOf, and a few other minor changes), however, editing the Shapes section is still not yet working. 

The now-fixed schema can be found [here](https://json-editor.github.io/json-editor/?schema=N4IgLglmA2CmIC4QGVZkgOwOYGcQBpwBPAB3iQHsAjAK1gGMwCQAnWARwFcI2ATRANopYOHBAoZmAMQosA7gEMW/QgHkSYCr3iFkACwVk8hACIUAtgoiSAuoQBmsy0yT0FYWFlkQRzEiwoyFkhfBFBUUXFJMOIyRBBqOkZmSBhyYUiJZkcWZ3isFggVVg5uPkEQAEkTZgAFPQpNDGMQMwBZCBxnej1mMwBBTk0AFT02BX47EH9A2GCfPBjqxFBUuHiIsQkAAgA5BXMdWPScMELsZm17BU5oFxBzegAPEABfQnrGiUXVqHWkT5NbYYTjmKhzFKkdLWDxYCGEK43O6IACMAAYMRjCJYnhBzKDUZiie9WhQOl13D0VuA/ukzNsAEqwexwRhRSFxJBUCgUOAKSQI5lIlxnTiwEkDIYUUbjfgxNbpAAyaG2bQAwgANbbaehFWDbMBjWATAD0VGgFHoAGttmIAF5HMBQ+Lc3nGgUgRG3EUsMUkhm7ADiqFgct+aXiDP5vAsttgoY56RBYPhJS4PATCGu0BwsEF129iAATABONEoosAZhLRdedcIMnkSjDx3iiQYTEICvijcUymyTnc+UKxTY6fKCCEwzRzGGKL6TCmMyCIR+IGn1O7SGQYCUmCwBrxjudSGT4JYlyFhYQaOx1jxBJv2IUuPx5lRsAAtAB2Elzze0vEACiGC8NYB6QIcibxGeqZesiCAAKxfiWd4YA+75Pg8L4YR+P4Si44b/OuR7bFg7j6nIRSGtBp6guel4FghyGfqhDz3m+iC3thr6PiiX6/vWIDqJo2ibieCS0B2KSAUgIlaEcY5lJmQjIBQnAsPQ8BLgEK4LNSakaVpAERtu6macenKSUknZpspcpTs6HwUC0Jg8CAOmzPMoSgMMJ5EekflxF2EmnOcWCMcK8RkBgurQMwsDJhUMVxcwnSNLpED0Mw9ASEc5GcJE/J+NA/JKH47geCwHokJVcwYJWxSOBpPgXoQSj0GIGBHGBOBWgOLVzC8Djma1TxFsUdoFUVHrQNYRw4HNtkpRApUsCwChEB5JK1C5JnEbtYiQFkIVWUoG1bSNuRDkgu5UC0UCwOYa5OlZsEXiS8EuAIla3r9+BolM5jWJUHjPYglbPk8oNPYslYSu58qySAio3LFejbG5bBsidrZIOdm0Dtd9x3S0X2CLet4olMj3g/KEnvW8aEw3TkM8SziwACw7UoBzzkjpkoOZWnbLUvOHFV2zzqd6QE5ddkZnK2a5ldeS3Qo91pWDL0M/REIksDGAc4gnNQ8bCDcx84tFvt6SGRZovi2gcxS7RIBy8wSmK4gyt5iAORq+AGsPdr4lvXrH3M6HFtm9H3NCSYzuMLItvxInHjJ21ePu+thOEF7E6+6rN1B+aRy0zrVntsk+elN7k4gIdzAMh5hDLnMq7Uk3AsHS5UDsjL8Qe4QFdh0mEdM+xRvR2zOLm/DhAtz36RRmBhVu4z+ZRQgRZobhN51ofJL6IYPk0oLJ9GG7w/+4OJMa+sI/R6A/JEKo9iCAF8SBiObvV7ZBcVLrgUBFXQEAHStxAKPGI7dvJrmGCA1OSAEGgOzjCTwqZDb7zRMfcB5Av7bjwdfXO8sA4l1JlrWGY8YITwNiDGescqEIHhoffABCUAkD0HMSy6R/6ezrhOKciC1DN0gbAzuMQUFIOAag160IMCwkwRxR8OCRHL3iGqRKVViEXSJoHChT8mGrF1imSOU956MNZv6aRq8IDr0HnRUxzAsGcQPvWdhAAhCgw1s58NruOIBUiRFgIgZ5PSZ8pHqOQcItBCiMFZxcSo3BECokoCIQ4nOuji7301oYumxjw5OLodPJhs8XzzxJKoaRmi4lZzkUPEhejyHB0ofk7OjNikWPZjPVh7DkCcCoAUIof8pI1wVoImRzAqkhO0m3XSHd9KSMQakoJsTFEJOUZhVRaSUl9PSdnG+ZCckhyMe02hUdSmWLhpU6pWjUz1Pxo07J8QDFQOfmcopFzWZXIhr08+xE1REDmqBe5Ek/HjMCTEtUM5CBqmliAFuYSFkROWew1ZDyoFxLhBs9CrjtnQukcgfZGLDl3xeS0vJldx6fPMQw7ppSSRwtubUnRedb7E3Jbkt5pyMUdK+XDH5zDrGpNsfYj5DE954r+VuEA+woIZLCuBN4NgE4WCsNEApvDRm2RlWYSw1h+EBIciANooYIAKD6HiKZhQsDWCCkcAAaryUEsApCrVmdMeZcDqSqBtXa/y/z0i+ogLajA2x3DbAEJTAGNg3auj5B6cmCBRTilMFa1JblDjNCiC0ElTz2X6IpdytpGL0HYsnkmqNAMY38ohoKheIAnXQBdW6/47Cm0uu2K2nh8RFUXC3teEAk9TVgQtakkd5rWWkLJerMuzj6FMN3sWqlbZtWGvshUfEFrsRitQbYOZXkJGgC3dI/o91ZAaCiNsAAFIAHuAFBSxNOYcwABKDeE8B0IW4okrZBt16pOQG4dAcxwI3tvTgR9z630ZM3p6K8X7JVJMIBFVJ/R0I4AyoEIgN6sDQfFXBeDLgUSIcwp+YjPF94ohJBqwNkZmSskgAAN31JUEFTwb0YDw7yj9cGmJEZI1xI+R8gA=&value=N4IgygpgzlCWD2A7EAuUBJAIqkBbAxgB4gA0IACgBbwAuSUqAjAAyutmbwCysUuAhjXyVUNAE4BXCB3gBBCXQAqlMRH4ATUZIgBfMgDF4YgO78xmtCEXNUzMosaoArBAC0ATg41nb93pAA8gAOdOoQqKBg8BJi+OGWigCeQfEgKYj4sAA2pBTwDCgA2gDMdqUkzAC6HLBiqIV2doyVOv5glPwpBYXVIJwCsMiWAWKwAOaDSSlaUjW49Y0VvQBq8FkSuBD62am5XBDqsPz1oLgSxyh2eBIFV2NMZEOMeqfntmRnt2T3KIyPTDoWjogA==&lib_switcher=&prompt_before_delete&upload=function(a,b,c){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction&required_by_default).

If one click on the "Shapes" tab, and click +row, the Grid object does not seem to be editable. If I switch it to Sphere using the drop down button, and then switch back to Grid, I see the editor panel contains subfields Tag/O/R, which are the sub-fields of Sphere instead of Grid. 

If one further choose Box from the dropdown menu, the displayed properties are Tag/Size/Center/R which seems to be merged of Grid and Sphere objects.

I am wondering if there is a problem the way how I defined these sub-item objects, or there is a bug in json editor?

again, the goal is to allow the `Shapes` section in my json input file to contain 0-many objects of different subfields, as shown in this example input file

https://github.com/fangq/mcx/blob/72afd6a0bebcca6a83735aa215d07125f1c5bee1/README.txt#L549-L582

thanks for your suggestions

**Comment by schmunk42** [comment] 2019-05-20 14:02
> If one click on the "Shapes" tab, and click +row, the Grid object does not seem to be editable. If I switch it to Sphere using the drop down button, and then switch back to Grid, I see the editor panel contains subfields Tag/O/R, which are the sub-fields of Sphere instead of Grid.

Could you try setting `keep_oneof_values` to `false`.

@pmk65: We don't have this option in the current demo and neither in the new one from you (https://pmk65.github.io/jedemov2/dist/demo.html) - or did I miss something?

Besides that, the behavior looks like a bug to me. It would be great if we could create a simpler test-case reproducing the problem with `anyOf` CC: @germanbisurgi

**Comment by fangq** [comment] 2019-05-20 15:56
hi @schmunk42, thanks for the quick reply. I tried to add the `keep_oneof_values:false` line in JSONEditor's constructor, but the observation remains the same, except that when I first click on any `+row` button, it gives me an error `Value must be one of the provided types`. 

A simple reproductor schema can be found below. What I expect to see is to use jsoneditor to add/remove/edit objects into the Shapes[] array construct. The objects (Grid, Sphere, Box, ...) have different titles and required sub-fields. What I see right now is that jsoneditor somehow could not properly list subfields for each selected sub-object, and generates a list of parameters that across multiple objects.

Let me know if you can reproduce this issue, and anything else I can try/provide. thanks again

```javascript
{
  "title": "Settings",
  "type": "object",
  "required": [
    "Shapes"
  ],
  "format": "categories",
  "properties": {
    "Shapes": {
      "title": "Shapes",
      "type": "array",
      "format": "table",
      "items": {
        "anyOf": [
          {
            "title": "Grid",
            "type": "object",
            "required": [
              "Tag",
              "Size"
            ],
            "items": {
              "properties": {
                "Tag": {
                  "title": "Tag",
                  "type": "integer",
                  "minimum": 0
                },
                "Size": {
                  "title": "Size",
                  "type": "array",
                  "format": "tabs",
                  "items": {
                    "type": "number"
                  },
                  "minItems": 3,
                  "maxItems": 3
                }
              }
            }
          },
          {
            "title": "Sphere",
            "type": "object",
            "required": [
              "Tag",
              "O",
              "R"
            ],
            "properties": {
              "Tag": {
                "title": "Tag",
                "type": "integer",
                "minimum": 0
              },
              "O": {
                "title": "Center",
                "type": "array",
                "format": "tabs",
                "items": {
                  "type": "number"
                },
                "minItems": 3,
                "maxItems": 3
              },
              "R": {
                "title": "Radius",
                "type": "number",
                "minimum": 0
              }
            }
          },
          {
            "title": "Box",
            "type": "object",
            "required": [
              "Tag",
              "O",
              "Size"
            ],
            "properties": {
              "Tag": {
                "title": "Tag",
                "type": "integer",
                "minimum": 0
              },
              "Size": {
                "title": "Size",
                "type": "array",
                "format": "tabs",
                "items": {
                  "type": "number"
                },
                "minItems": 3,
                "maxItems": 3
              },
              "O": {
                "title": "Center",
                "type": "array",
                "format": "tabs",
                "items": {
                  "type": "number"
                },
                "minItems": 3,
                "maxItems": 3
              }
            }
          },
          {
            "title": "Subgrid",
            "type": "object",
            "required": [
              "Tag",
              "O",
              "Size"
            ],
            "properties": {
              "Tag": {
                "title": "Tag",
                "type": "integer",
                "minimum": 0
              },
              "Size": {
                "title": "Size",
                "type": "array",
                "format": "tabs",
                "items": {
                  "type": "number"
                },
                "minItems": 3,
                "maxItems": 3
              },
              "O": {
                "title": "Center",
                "type": "array",
                "format": "tabs",
                "items": {
                  "type": "number"
                },
                "minItems": 3,
                "maxItems": 3
              }
            }
          },
          {
            "title": "Cylinder",
            "type": "object",
            "required": [
              "Tag",
              "C0",
              "C1",
              "R"
            ],
            "properties": {
              "Tag": {
                "title": "Tag",
                "type": "integer",
                "minimum": 0
              },
              "C0": {
                "title": "Size",
                "type": "array",
                "format": "tabs",
                "items": {
                  "type": "number"
                },
                "minItems": 3,
                "maxItems": 3
              },
              "C1": {
                "title": "Center",
                "type": "array",
                "format": "tabs",
                "items": {
                  "type": "number"
                },
                "minItems": 3,
                "maxItems": 3
              },
              "R": {
                "title": "Radius",
                "type": "number",
                "minimum": 0
              }
            }
          },
          {
            "title": "Name",
            "type": "string"
          }
        ]
      }
    }
  }
}
```

**Comment by pmk65** [comment] 2019-05-20 18:05
> 
> @pmk65: We don't have this option in the current demo and neither in the new one from you (https://pmk65.github.io/jedemov2/dist/demo.html) - or did I miss something?
> 
You are correct. I must have missed that one. It's now available at the Playground page.

**Comment by schmunk42** [comment] 2019-05-20 21:47
Nice! So I think, at least the switching works better with this option, but there's still an issue with initialization of `anyOf` and I think also `oneOf` items.

**Comment by fangq** [comment] 2021-03-04 00:35
I would like to give an update to this issue - I figured out how to properly define json-schema to for arrays of objects, such as examples shown here:

https://github.com/fangq/mcx/blob/72afd6a0bebcca6a83735aa215d07125f1c5bee1/README.txt#L549-L582

with the updated json schema, I was able to get valid inputs using either json editor's default interface, 

http://tinyurl.com/y9vynjxy

or using the json editor playground link

http://tinyurl.com/ymr9bzhn

however, I found one issue (which sort persisted from previous observations) - if you click on the "Shapes" tab, click "+row", if you select any object other than "Grid", for example, "Sphere", you will see an extra "Grid" object attached at the bottom of the desired object.  A screenshot is attached.

Currently, json editor outputs this JSON construct
`"Shapes":[{"Sphere":{...}, "Grid": {...}}]`
but the desired output is
`"Shapes":[{"Sphere":{...} }]`

or, if multiple objects shall be included, I need
`"Shapes":[ {"Grid": {...}}, {"Sphere":{...}} ]`

in your opinion, is this a bug in my json schema definition, or json editor? my schema is defined here

https://github.com/fangq/mcx/blob/master/schema/mcxinput.json

**Comment by schmunk42** [comment] 2021-03-04 21:03
Pretty complex schema :) 

I do not really understand the problem, eg. with *desired output*. there's just a additional closing bracket `}`
Same for multiple options.

Could you create a small schema which reproduces the problem with "Shapes"?

**Comment by pmadril** [comment] 2021-03-05 06:30
@fangq If you set the "No additional object properties" option, you solve your problem.
I went through this some time ago.

A simple schema showing the problem:
`{
  "title": "Settings",
  "type": "object",
  "required": [
    "Shapes"
  ],
  "properties": {
    "Shapes": {
      "title": "Shapes",
      "type": "array",
      "format": "table",
      "items": {
        "anyOf": [
          {
            "title": "Grid",
            "type": "object",
            "required": [
              "Grid"
            ],
            "properties": {
              "Grid": {
                "title": "Grid",
                "type": "object",
                "required": [
                  "Tag"
                ],
                "properties": {
                  "Tag": {
                    "title": "Tag",
                    "type": "integer",
                    "minimum": 0
                  }
                }
              }
            }
          },
          {
            "title": "Sphere",
            "type": "object",
            "required": [
              "Sphere"
            ],
            "properties": {
              "Sphere": {
                "title": "Sphere",
                "type": "object",
                "required": [
                  "R"
                ],
                "properties": {
                  "R": {
                    "title": "Radius",
                    "type": "number",
                    "minimum": 0
                  }
                }
              }
            }
          },
          {
            "title": "Box",
            "type": "object",
            "required": [
              "Box"
            ],
            "properties": {
              "Box": {
                "title": "Box",
                "type": "object",
                "required": [
                  "Tag"
                ],
                "properties": {
                  "Tag": {
                    "title": "Tag",
                    "type": "integer",
                    "minimum": 0
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}`

I think there is a real problem, but I don't have time to dig it up. As far as I remembered, there is an array of objects that must  be cleaned of dangling references.
The phantom "Grid" object that appears is not a real "Grid" object because type of its properties are not defined. 
So the UI shows a type selector, beside the property title, for all the phantom "Grid" properties.
It's the same thing as dynamic adding a new property.

May be this helps.

**Comment by fangq** [comment] 2021-03-05 16:13
thank you @pmadril , the "No additional object properties" option indeed solved the problem! thank you very much. I will leave this ticket open so you can use it to track this issues down in the future. thanks again!

**Closed** 2021-03-29 13:54 UTC
Labels: bug, help wanted
