### ISSUE TITLE
Objects with '.' characters in keys display with truncated/trimmed keys

### ISSUE THREAD

**Issue by disalvjn** [json-editor/json-editor#231] opened 2018-11-30 22:15 UTC
Thanks for the great library -- it's saving me so much time manually writing complicated editors. 

### Expected behavior

Schema:
```js
{
  "title": "JVM Arguments",
  "type": "object",
  "required": [
    "-Dsun.rmi.dgc.ackTimeout"
  ],
  "properties": {
    "-Dsun.rmi.dgc.ackTimeout": {
      "type": "string"
    }
  }
}
    
```
Object:
```js
{
  "-Dsun.rmi.dgc.ackTimeout": "10000"
}
```

I'd expect the form to use `-Dsun.rmi.dgc.ackTimeout` instead of `ackTimeout` for the header. 

It looks like this has something to do with path computations splitting on '.'

Normally I'd try find a different separator to use, but since my editor is showing JVM arguments, I don't have a choice except to display with '.'s. 

### Actual behavior
![dotinobjectkeyjvm](https://user-images.githubusercontent.com/7563067/49317393-4bf54c80-f4c2-11e8-979f-e4f25b853775.PNG)

**Comment by schmunk42** [comment] 2018-11-30 22:30
You can use `headerTemplate` to display any title you want.

**Comment by pmk65** [comment] 2018-12-02 13:56
> 
> 
> You can use `headerTemplate` to display any title you want.

The problem is not the title, but that he is using dots in the field names.
This is just not possible as JSON-Editor uses dots as a separator between identifiers.

If you have a field in you schema named "test", JSON-Editor refers to this as "root.test"
So if you name your field "te.st", JSON-Editor won't be able to separate the various parts of the identifier,

**Comment by disalvjn** [comment] 2018-12-02 23:13
My specific use case is a UI for adding JVM arguments to a server. So, I'd like users to be able to add arbitrary key-value pairs (command line arguments), where the keys may contain dots. 

If I'm displaying a read-only version, I can dynamically generate the schema, then filter for dots. But is there a way to safeguard against a user adding an arbitrary key with a dot in it, other than displaying a message above the editor telling them to use a substitute character (which is probably an impossible sell to management)?

Can JSON-Editor use a vector instead of a '.' joined string (and if you need a string to identify elements in HTML, just json-print the vector), or, if it has to be a string, use a much less common string-sequence, like '$JEsplit$' instead of '.'? I know it's used for enabling and disabling parts of the editor, but why couldn't a user pass a vector in there, instead of a '.' separated string? And if they're passing in a vector, you can use an obscure joining string.

**Comment by pmk65** [comment] 2018-12-02 23:32
Currently, the dot usage is hardcoded in src/editor.js (try searching for **.split('.')** ), but I don't see any reason why this can't be overridden with a custom string/character.

You are welcome to extend it and create a PR.
Looks like src/editor.js is the only file that needs to be changed, so it shouldn't be that hard. 😉

**Comment by pmk65** [comment] 2018-12-02 23:34
**.split('.')**

**Comment by co16353sidak** [comment] 2019-02-16 17:22
Would love to work on this if no one else isn't. @pmk65

**Comment by pmk65** [comment] 2019-02-16 19:03
@co16353sidak I can see that @disalvjn did some work on this, see: https://github.com/disalvjn/json-editor/commit/417070eb2ffd34f1f95d9ea24d74879b27ab47fa
But since he never committed it to the main repo, I guess you can take over if you want.

**Comment by pmk65** [comment] 2019-02-16 19:13
@co16353sidak Just remember that it MUST be using "." as default. (in order to preserve backward compatibility) So you will need to have an option to change it if needed. 
(Like: `JSONEditor.defaults.options.seperator = <blah blah>`)

**Comment by disalvjn** [comment] 2019-02-18 16:50
@co16353sidak @pmk65 I basically did a find-replace on `'.'` and changed it to something like `'json-editor-separator'`. 

That may not complete the feature; perhaps the functions that take paths (which include: `editor.disable`, `editor.enable`, `editor.watch`, `editor.unwatch`, `editor.getEditor`) might support taking an array, so that the library can join the path constituents together with the path separator, rather than the user.

I wound up not pursuing it further, because for my use case, which is somewhat orthogonal to this issue, I also wanted users to be able to add/remove key-value pairs from objects. So I switched to using Lists of key-value pairs, as this was the simplest solution. 

@co16353sidak You are more than welcome to work on this.

**Comment by pmk65** [comment] 2019-06-18 14:28
I think I got this solved by correcting the key value so it allows for dots.

**Closed** 2019-06-18 14:55 UTC
Labels: enhancement, good first issue
