### ISSUE TITLE
"npm run start" - Start Webpack server doesn't produce output

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#495] opened 2019-08-24 13:21 UTC
When I run **npm run start**, to start the Webpack server, I get this output:

> npm run start

> @json-editor/json-editor@1.4.0-beta.0 start C:\GITHub\json-editor
> webpack-dev-server --config config/webpack.dev.js --progress

> 10% building 1/1 modules 0 activei ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /dist/
i ｢wds｣: Content not from webpack is served from C:\GITHub\json-editor
i ｢wds｣: 404s will fallback to /index.html
i ｢wdm｣: Hash: 8f5eab5eadb3883f8836
Version: webpack 4.39.1
Time: 3590ms
Built at: 2019-08-24 15:10:26
        Asset      Size      Chunks             Chunk Names
jsoneditor.js  2.09 MiB  jsoneditor  [emitted]  jsoneditor
Entrypoint jsoneditor = jsoneditor.js
[0] multi (webpack)-dev-server/client?http://localhost:8080 ./src/core.js 40 bytes {jsoneditor} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {jsoneditor} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 4.29 KiB {jsoneditor} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {jsoneditor} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {jsoneditor} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.85 KiB {jsoneditor} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {jsoneditor} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {jsoneditor} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {jsoneditor} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {jsoneditor} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {jsoneditor} [built]
[./src/core.js] 27.7 KiB {jsoneditor} [built]
[./src/defaults.js] 16.8 KiB {jsoneditor} [built]
[./src/editor.js] 19.2 KiB {jsoneditor} [built]
[./src/editors/ace.js] 2.91 KiB {jsoneditor} [built]
    + 98 hidden modules
i ｢wdm｣: Compiled successfully.

I'm assuming it should work similar to **grunt watch**, but no files are generated or updated in the dist folder when I make modifications to the source files in `/src`. But I can see saving triggers the Webpack server to recompile.

> Version: webpack 4.39.1
Time: 177ms
Built at: 2019-08-24 15:15:37
        Asset      Size      Chunks             Chunk Names
jsoneditor.js  2.09 MiB  jsoneditor  [emitted]  jsoneditor
Entrypoint jsoneditor = jsoneditor.js
[./src/editors/string.js] 10.2 KiB {jsoneditor} [built]
    + 112 hidden modules
i ｢wdm｣: Compiled successfully.

(**npm run build** and **npm run build.dev** works.)

**Comment by pmk65** [comment] 2019-08-24 19:24
**Sidenote:** 

**npm run build** creates 2 files in `dist/` - `jsoneditor.js` and` jsoneditor.js.map`
**npm run build.dev** creates 1 file in `dist/` - `jsoneditor.js`

But shouldn't **npm run build.dev** also create the map file for development/debugging use?

So **npm run build.dev** would creates 2 files in `dist/` - `jsoneditor.js` and` jsoneditor.js.map`
and **npm run build** would creates 4 files in `dist/` - `jsoneditor.js`, ` jsoneditor.js.map`,  `jsoneditor.min.js` and` jsoneditor.min.js.map` (Once the minify process is implemented)

**Comment by pmk65** [comment] 2019-08-24 22:46
Adding `writeToDisk: true` to `devServer` object, in `config/webpack.dev.js` fixes the problem with file not getting created on disk.

**Comment by sirockin** [comment] 2019-08-25 06:52
@pmk65 thanks for the feedback.

Yes the default with using the dev server is not to write to disk - the point about running dev server is to very quickly rebuild and serve the distribution as changes get made - not to build an output. You can of course always build the actual output by running webpack instead of webpack-dev-server.

Since you asked for a non-minified distribution, I've added a nonmin build type which does produce non-minified output in a subdirectory of the main one. I'm looking at how best to create code for this distribution which is both optimised and debuggable via source maps. TBH this is a bit out of my comfort zone - I've never really dealt with a situation where there is a requirement to debug *distributed* code as part of the standard development lifecycle.

I think what I'm going to do is submit a PR tomorrow with just these added distributions (and none of the lazy-loading stuff because that is quite high impact - I'll raise a separate issue on that). Then you can adjust the builds as you see fit. (Remember I'm no more a webpack expert than you, and given your experience with the project and your understanding of the development use cases, you're probably the best person to tweak these builds).

**Comment by pmk65** [comment] 2019-08-25 08:37
It is very common to distribute both a minified and an un-minified version, specially on CDNs.
People using the CDN version might not know how to create a custom, but we still want them to report bugs. 
Example: https://www.jsdelivr.com/package/npm/@trevoreyre/autocomplete-js?path=dist

_Maybe I'm using the Webpack server wrong. But I can't figure out how to use it/debug when there's no file. What do I link to in the HTML file?_

**Comment by sirockin** [comment] 2019-08-25 12:54
Hi @pmk65. Running `npm start` should serve files from 8080. The way it is set up is that built files should serve to `localhost:8080/dist` (they are served from memory so no need for them to be in the actual dist folder) and the rest of the repo should just serve from `localhost:8080/{path of file}.

So to debug (say) one of the files in the test directory you simply navigate to http://localhost:8080/tests/pages/array-selectize.html. Since the script tag already points to `./dist/jsoneditor.js`, the generated output files should just load.

Since there is no index.html file in the root of the repo (and the test server doesn't provide file indexing)  if you just point at http://localhost:8080 you *will* get an error. For me it's (as expected) a 404, with the text body: `Cannot GET / `. I've never seen the 426 error. Can you provide a screenshot or upload the html source of the message?

**Comment by sirockin** [comment] 2019-08-25 16:20
See also my remarks in `./config/readme.md` in #498

**Comment by pmk65** [comment] 2019-08-25 17:05
There's no HTML page, just the text "Upgrade Required". I only noticed the 426 error when I looked at the headers. That's all the info there is.

**Comment by sirockin** [comment] 2019-08-25 17:08
What happens when you navigate to a valid url such as http://localhost:8080/tests/pages/array-selectize.html?

If this doesn't work, can you try deleting your `node_modules` folder then running `npm install`?

**Comment by pmk65** [comment] 2019-08-25 17:52
![image](https://user-images.githubusercontent.com/478711/63653741-0b84df80-c771-11e9-8ffc-96f3757bd3fa.png)

i get the same result no matter what path I put in.

And I have removed the `node_modules` folder before running `npm install` as you suggested, but no changes.
Still getting these warnings after `npm install`

> npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-import@2.9.0 requires a peer of eslint@2.x - 4.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@7.7.0 requires a peer of eslint@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by pmk65** [comment] 2019-08-25 18:28
Server is running without errors. 
And if I add `writeToDisk: true` it will generate/update the file when I make changes, so it is running.

**Comment by sirockin** [comment] 2019-08-26 06:49
On the 426 error, I just did a search and found 

* this issue: https://github.com/webpack/webpack-dev-server/issues/1446 which isn't super-helpful

* this info: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/426

I've just tried doing a fresh clone, switching to `develop/2.0` and building and was unable to reproduce your npm install errors. However the acorn warning seems to be an npm bug: https://github.com/webpack/webpack/issues/8779

Please could you try: 

1. Upgrade npm and node to latest versions
1. Make a fresh clone of the repo, switch to `develop/2.x` and run npm install again

If that produces install errors, please post these here.

Then:

1. Run `npm start` and navigate again to http://localhost:8080/tests/pages/array-selectize.html. 
1. If you get the same `Update Required` page,  right click on the page in your brosers and choose `View Page Source` from the context menu, then attach the resulting html here.
1. Check your Firefox version - Could it be that needs updating?

1. Please also give me your OS type and version no - I will try and replicate

Cheers

**Comment by pmk65** [comment] 2019-08-26 21:57
Everything is latest version, EXCEPT Nodejs. And once I updated that, the server worked. (Nodejs for windows suck when it comes to updating. As there is no auto update or reminders like with npm. You'll have to download and reinstall it. 🚽 )

The nodejs update solved the various npm error/warnings too,

Thanks for your help..

**Comment by sirockin** [comment] 2019-08-27 06:43
Hi @pmk65.
> The nodejs update solved the various npm error/warnings too,
 
Glad that worked.

> Could you add an extra script with the writeToDisk: true for the server (maybe it could be a switch when you run the server script?), so we have something that mimics the old grunt watch setup?

 I *can* add that to the start script but it may slow down the watch/build/serve lifecycle and I'm not clear on what use it is since the point of `start` is to allow round-trip debugging. Did you notice I've added a `build.dev` script in #498 - that does produce buiild output if and when you want it. Does that not meet your requirements?

**Comment by pmk65** [comment] 2019-08-27 11:55
It depends on how you use (or debug) the library. The e2e tests won't do any good when you are adjusting the CSS/HTML output. 
Most JSON-Editor users are familiar with the old `grunt` setup, so it's a big difference when there's no actual file created. And they might have a testing setup based on the existence of an actual file. 

I use the Playground page for testing output and complex setups by linking to the `dist/` files when doing builds. That way I can quickly test the output using some of the pre-made examples. 

So if we have both options available, everyone will be happy. 😁

**Comment by sirockin** [comment] 2019-08-27 13:11
I'm worried we're producing a plethora of builds and scripts for use cases that I don't really understand.

Here's what I propose:

I will rename all the `start` scripts to `debug`.

I will then create a new `start` script that builds nonmin in watch mode but doesn't serve the output - I think I'm right in thinking that's how the old `start` script works.

If that doesn't work for you maybe it would be better if you submit a PR with it setup exactly how you want it.

**Comment by sirockin** [comment] 2019-08-28 08:31
@pmk65 any thoughts on my last comment?

**Comment by pmk65** [comment] 2019-08-28 10:22
@sirockin Let's try it out.

**Comment by sirockin** [comment] 2019-08-28 16:35
@pmk65 I've just merged latest updates to #498. Please could you close this when you're happy?

**Closed** 2019-08-29 18:56 UTC
Labels: 2.x, bug, webpack
